name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - staging
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  dev:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Plan
        run: terraform plan --var-file="terraform.tfvars.dev" -out="main.dev.tfplan"

      - name: Terraform Apply
        run: terraform apply "main.dev.tfplan" -auto-approve

      - name: Test Web Endpoint
        run: curl "http://$(terraform output -raw gateway-public-ip-address)"

      - name: Get Web Endpoint
        run: echo "Dev Web Endpoint: http://$(terraform output -raw gateway-public-ip-address)"

  staging:
    needs: dev
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform workspace
        run: terraform workspace select staging || terraform workspace new staging

      - name: Terraform Plan
        run: terraform plan --var-file="terraform.tfvars.staging" -out="main.staging.tfplan"

      - name: Terraform Apply
        run: terraform apply "main.staging.tfplan" -auto-approve

      - name: Test Web Endpoint
        run: curl "http://$(terraform output -raw gateway-public-ip-address)"

      - name: Get Web Endpoint
        run: echo "Dev Web Endpoint: http://$(terraform output -raw gateway-public-ip-address)"
